In [40]:
a = int(input())

3


In [42]:
print(a)

3


In [3]:
print("Hello World")

Hello World


In [43]:
for i in range (a+1):
    for x in range(i):
        print(x+1,end='')
    print('')


1
12
123


In [47]:
for i in range (a+1):
    for x in range(i):
        print(i,end='')
    print('')


1
22
333


# Title L1
## Another Title L2
### Title L3

* First Point
* Second Point

####  HI

In [72]:
name = str(input())

Afraj


In [76]:
print(len(name))

5


In [86]:
if(len(name)>=5):
    print(name)
else:
    print("Invalid")

Afraj


In [54]:
price = float(input())

12.99


In [55]:
age = int(input())

21


In [88]:
print ("Hi Im "+name+" and Im "+str(age)+" years old")

Hi Im Afraj and Im 21 years old


In [92]:
def add( a, b):
    return a+b

In [93]:
add(3,1
   )

4

In [95]:
import numpy as np

In [121]:
a = np.array([[1,2,3,4,5,6],[3,2,1,3,3,3],[2,1,2,1,2,1]],dtype=np.float64
            )

In [136]:
for i in range(len(a)):
    print(a[i])

[1. 2. 3. 4. 5. 6.]
[3. 2. 1. 3. 3. 3.]
[2. 1. 2. 1. 2. 1.]


In [101]:
a.dtype

dtype('float64')

In [137]:
len(a
   )

3

In [122]:
a

array([[1., 2., 3., 4., 5., 6.],
       [3., 2., 1., 3., 3., 3.],
       [2., 1., 2., 1., 2., 1.]])

In [135]:
a.ndim


2

In [119]:
a.shape

(2, 6)

In [133]:
a.size

18