In [1]:
import numpy as np


## Create Matrix using numpy libarary

In [9]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
b = np.array([[5,6],[7,8]])
print(b)

[[5 6]
 [7 8]]


##Matrix Addition

In [11]:
a+b

array([[ 6,  8],
       [10, 12]])

##Matrix Subraction

In [12]:
a-b

array([[-4, -4],
       [-4, -4]])

##Matrix Multiplication (Hadamald Product)

In [13]:
a*b

array([[ 5, 12],
       [21, 32]])

##Matrix Multiplication (Dot Product)

In [14]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

##Matrix Subtraction

In [15]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

##Transpose a matrix




In [17]:
m = np.array([[1,2],[3,4],[5,6]])
print(m)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
### T is used to Transpose a matrix
m.T

array([[1, 3, 5],
       [2, 4, 6]])

## Inverse of a matrix

In [20]:
a


array([[1, 2],
       [3, 4]])

In [21]:
inmat = np.linalg.inv(a)
inmat

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Trace of a Matrix

In [22]:
a

array([[1, 2],
       [3, 4]])

In [24]:
np.matrix.trace(a)
## matrix left to right diagnal values added

5

## Determinant of a 2*2 Matrix

In [25]:
a

array([[1, 2],
       [3, 4]])

In [27]:
np.linalg.det(a)

-2.0000000000000004

##EigenValue and EigenVector 

In [31]:
eigenvalue,eigenvector = np.linalg.eig(a)
print("Eigenvalue : ",eigenvalue)
print("Eigenvector : ",eigenvector)

Eigenvalue :  [-0.37228132  5.37228132]
Eigenvector :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
