In [ ]:
import numpy as np


## Create Matrix using numpy libarary

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
b = np.array([[5,6],[7,8]])
print(b)

[[5 6]
 [7 8]]


##Matrix Addition

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

##Matrix Subraction

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

##Matrix Multiplication (Hadamald Product)

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

##Matrix Multiplication (Dot Product)

In [ ]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

##Matrix Subtraction

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

##Transpose a matrix




In [ ]:
m = np.array([[1,2],[3,4],[5,6]])
print(m)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
### T is used to Transpose a matrix
m.T

array([[1, 3, 5],
       [2, 4, 6]])

## Inverse of a matrix

In [ ]:
a


array([[1, 2],
       [3, 4]])

In [ ]:
inmat = np.linalg.inv(a)
inmat

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Trace of a Matrix

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.matrix.trace(a)
## matrix left to right diagnal values added

5

## Determinant of a 2*2 Matrix

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.linalg.det(a)

-2.0000000000000004

##EigenValue and EigenVector 

In [ ]:
eigenvalue,eigenvector = np.linalg.eig(a)
print("Eigenvalue : ",eigenvalue)
print("Eigenvector : ",eigenvector)

Eigenvalue :  [-0.37228132  5.37228132]
Eigenvector :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


##Train

In [52]:
import tensorflow as tf

from google.colab import drive
drive.mount("/content/drive/")

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [51]:
import pandas as pd
data = pd.read_csv('/content/drive/My Drive/Dataset/Cars.csv',usecols=['Milage','Year'],nrows=4)
data

Milage  Year
0  340544  2011
1  403432  2011
2  375033  2011
3  349643  2011

In [53]:
## CONVERT THE FEATURES TO TENSORFLOW FLOAT32

features = tf.convert_to_tensor(data,dtype=tf.float32)
features

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[340544.,   2011.],
       [403432.,   2011.],
       [375033.,   2011.],
       [349643.,   2011.]], dtype=float32)>

In [55]:
weights = tf.constant([2,0.5],shape=[2,1])
weights

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2. ],
       [0.5]], dtype=float32)>

In [56]:
featuresXweights = np.matmul(features,weights)
featuresXweights

array([[682093.5],
       [807869.5],
       [751071.5],
       [700291.5]], dtype=float32)

In [59]:
fxw = featuresXweights + 7.5

In [61]:
intfxw = tf.convert_to_tensor(fxw,dtype=tf.int32)

In [62]:
intfxw

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[682101],
       [807877],
       [751079],
       [700299]], dtype=int32)>